name: Front side

on:
  workflow_dispatch:

jobs:
  print-numbers:
    runs-on: ubuntu-latest

    steps:
      - name: Print Numbers
        run: |
          for i in {1..20}
          do
            echo "N: $i"
          done 
